### ISSUE TITLE
[BUG] Ridiculously small counter limit

### ISSUE THREAD

**Issue by ErikUden** [codingneko/NuTracker#40]
​

**Comment by codingneko** [comment]
Honestly at that point you're basically just cheating, so it's a good thing the app breaks. It prevents the app from being DDoSed by adding infinite nuts.

I also have some doubts about whether you actually tried this because as you would've known if you had actually read the code, nothing is coded in Java here. The back end is JavaScript and the database is MongoDB. I don't believe either of them have a limit for number size. At least not one reachable by a human, JavaScript's MAX_VALUE is 1.7976931348623157e+308
